### ISSUE TITLE
Web docroot may not be created initially and all files we be installed at root

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-starter#1]
On initial install, the web docroot was not created, so Drupal and Express were not moved.

**Comment by alexfinnarn** [comment]
The build script has to be run in the project's root or else the structure isn't setup correctly. Ideally this would happen on `lando start`; however the link to `/var/www/html` would have to be linked back to your local machine to be visible.

**Comment by alexfinnarn** [comment]
Looking at this again https://github.com/CuBoulder/express-starter/blob/master/scripts/build-express.sh#L14 should create the web folder correctly if there isn't one there already. 

I set it up this way since the dot files, e.g. ".htaccess", weren't being copied over so using `mv` seemed more appropriate. 

The PR should make "web/drupal-${version}" instead of renaming the Drupal folder into "web" so I am closing it.
